name: API Automation CI (Docker)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test-in-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t bookstore-api-tests:ci .

      - name: Run tests in Docker (generate Allure report)
        env:
          BASE_URL: https://fakerestapi.azurewebsites.net/api/v1
        run: |
          mkdir -p out
          
          docker run --rm \
          -e BASE_URL="${BASE_URL}" \
          -v "${{ github.workspace }}/out:/out" \
          bookstore-api-tests:ci \
          bash -lc '
          set +e
          mvn -q clean test -Dallure.results.directory=/out/allure-results
          TEST_EXIT=$?
          set -e
          
          mvn -q allure:report \
          -Dallure.results.directory=/out/allure-results \
          -Dallure.report.directory=/out/allure-report
          
          exit $TEST_EXIT
            '

      - name: Upload Allure report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: out/allure-report/

      - name: Upload raw Allure results artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: out/allure-results/
